// automatically generated by the FlatBuffers compiler, do not modify

package message

const (
	MessageTypeCompile = 0
	MessageTypeRun = 1
	MessageTypeRegisterModule = 2
)

var EnumNamesMessageType = map[int]string{
	MessageTypeCompile:"Compile",
	MessageTypeRun:"Run",
	MessageTypeRegisterModule:"RegisterModule",
}

